server:
  port: 11002
spring:
  application:
    name: product-client
ribbon:
  eureka:
    enable: true
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    #?????? true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:11000/eureka
feign:
  hystrix:
    enabled: true